name: deploys

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://slipbox.rayriffy.com
    steps:
      - uses: actions/checkout@v4

      - name: docker
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/rayriffy/slipbox
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: deploy
        uses: deploys-app/deploys-action@v1
        with:
          project: rayriffy
          location: gke.cluster-rcf2
          name: slipbox
          image: ghcr.io/rayriffy/slipbox
          minReplicas: 1
          maxReplicas: 1
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
